# Generated by Django 2.1.5 on 2019-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
